=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b5p1-vjp-walterML-master/horariosescolar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
       <xs:appinfo>IES VJP - PLASENCIA - LMSGI - 1.0</xs:appinfo>
       <xs:documentation xml:lang="es">
           Schema para validación de documentos XML con horarios escolares por grupo, elaborado por <strong>Walter ML</strong>
       </xs:documentation>
       <xs:documentation xml:lang="en">
           Schema for validating XML documents with school schedules by group, prepared by <strong>Walter ML</strong>
       </xs:documentation>
  </xs:annotation>
  <xs:element name="Nombre" type="xs:string"/>
  <xs:element name="Url" type="xs:anyURI"/>
  <xs:element name="Periodo">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:time" name="desde" use="optional"/>
          <xs:attribute type="xs:time" name="hasta" use="optional"/>
          <xs:attribute type="xs:string" name="abbr" use="optional"/>
          <xs:attribute type="tipoPeriodo" name="tipo" use="optional" default="módulo"/>
          <xs:attribute type="xs:string" name="descripcion" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoPeriodo">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse" />
      <xs:enumeration value="módulo" />
      <xs:enumeration value="descanso" />
      <xs:enumeration value="activo" />
    </xs:restriction>
</xs:simpleType>
  <xs:element name="Dia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Periodo" maxOccurs="7" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute type="diaSemana" name="nombre" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="diaSemana">
   <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse" />
      <xs:enumeration value="Lunes" />
      <xs:enumeration value="Martes" />
      <xs:enumeration value="Miércoles" />
      <xs:enumeration value="Jueves" />
      <xs:enumeration value="Viernes" />
   </xs:restriction>
</xs:simpleType>
<xs:element name="Profesor">
  <xs:complexType mixed="true">
    <xs:sequence>      
      <xs:element ref="Dia" minOccurs="0" maxOccurs="7">
        <xs:annotation>
       <xs:documentation>Días y horas en las que contestará a los mensajes que reciba en los contactos</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:group ref="Contacto" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>
  <xs:element name="Modulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Profesor"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="abbr" use="optional"/>
      <xs:attribute type="xs:string" name="nombre" use="optional"/>
      <xs:attribute type="xs:unsignedShort" name="horas" use="optional"/>
    </xs:complexType>
  </xs:element>
 <xs:element name="Tutoria">
   <xs:complexType>
      <xs:all>
        <xs:element ref="Dia" />
        <xs:element ref="Profesor" minOccurs="1"/>
        <xs:element ref="Ubicacion" minOccurs="0"/>
        <xs:element name="Observaciones" type="xs:string" minOccurs="0"/>
        <xs:element name="DocenteTitular" minOccurs="0">
           <xs:complexType />
        </xs:element>
      </xs:all>
   </xs:complexType>
 </xs:element>
<xs:element name="Ubicacion">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse" />
      <xs:minLength value="10" />
      <xs:maxLength value="100" />
    </xs:restriction>
  </xs:simpleType>
</xs:element> 
  <xs:element name="Modulos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Modulo" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Horario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Dia" maxOccurs="5" minOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<xs:element name="IES">
 <xs:complexType>
    <xs:sequence>
      <xs:element ref="Nombre"/>
      <xs:element ref="Url"/>
      <xs:group ref="Contacto" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="codigo" use="optional" type="tipoCodigo"/>
  </xs:complexType>
</xs:element>
  <xs:simpleType name="tipoCodigo">
   <xs:restriction base="xs:positiveInteger">
      <xs:totalDigits value="10"/>
   </xs:restriction>
</xs:simpleType>
  <xs:element name="Grupo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tutoria"/>
        <xs:element ref="Modulos"/>
        <xs:element ref="Horario"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="nombre" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="HorarioEscolar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="IES"/>
        <xs:element ref="Grupo" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="curso"/>
      <xs:attribute type="xs:date" name="fechaCreacion"/>
    </xs:complexType>
  </xs:element>

  <xs:group name="Contacto">
  <xs:choice>
    <xs:element name="Telefono">
      <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="xs:positiveInteger">
             <xs:attributeGroup ref="attrContacto" />
           </xs:extension>
        </xs:simpleContent>
      </xs:complexType>
    </xs:element>
    <xs:element name="Mail">
      <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="emailAddress">
             <xs:attributeGroup ref="attrContacto" />
           </xs:extension>
         </xs:simpleContent>
       </xs:complexType>
    </xs:element>
  </xs:choice>
</xs:group>
<xs:simpleType name="emailAddress">
  <xs:restriction base="xs:string">
 <xs:pattern value="[A-Za-z0-9_]+([-+.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*\.[A-Za-z0-9_]+([-.][A-Za-z0-9_]+)*" />
  </xs:restriction>
</xs:simpleType>
<xs:attributeGroup name="attrContacto">
 <xs:attribute name="corporativo" type="xs:boolean"></xs:attribute>
 <xs:attribute name="idiomas" type="listaIdiomas" default="es-ES"/>
</xs:attributeGroup>
<xs:simpleType name="listaIdiomas">
  <xs:list itemType="xs:language"/>
</xs:simpleType>

</xs:schema>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b5p1-vjp-walterML-master/horariosescolar.xml
<?xml version="1.0" encoding="utf-8"?>
<HorarioEscolar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="horariosescolar.xsd" curso="2022-2023" fechaCreacion="2023-05-12">
    <IES>
        <Nombre>IES Valle del Jerte</Nombre>
        <Url>http://iesvjp.es</Url>
        <Telefono>1</Telefono>
        <Mail>consulta@iesvjp.es</Mail>
        <Mail corporativo="true" idiomas="es-ES">consultawsdfas@iesvjp.es</Mail>
        <Telefono corporativo="true" idiomas="es-ES">63977227845</Telefono>
    </IES>
    <Grupo nombre="1º ASIR">
        <Tutoria>
            <Dia nombre="Lunes">
                <Periodo desde="15:20:00" hasta="16:15:00" />
            </Dia>
            <Profesor>Tomás Montero
                <Dia nombre="Lunes">
                    <Periodo desde="15:20:00" hasta="16:15:00"></Periodo>
                </Dia>
                <Mail corporativo="true" idiomas="es-ES">tomas@iesvjp.es</Mail>
                <Telefono idiomas="es-ES">9274658965</Telefono>
            </Profesor>
            <DocenteTitular />
            <Ubicacion>En el dpto. de IyC</Ubicacion>
            <Observaciones>Algún comentario</Observaciones>
        </Tutoria> 
        <Modulos>
            <Modulo abbr="LMSGI" nombre="Lenguaje de Marcas y Sistemas de Gestión de la Información"  horas="128">
                <Profesor>Antonio Berrocal Piris</Profesor>
            </Modulo>
            <Modulo abbr="ISO" nombre="Implantación de Sistemas Operativos" horas="224">
                <Profesor>Antonio Berrocal Piris</Profesor>
            </Modulo>
            <Modulo abbr="PARE" nombre="Planificación y Administración de Redes" horas="224">
                <Profesor>Montaña Morales</Profesor>
            </Modulo>
            <Modulo abbr="GBD" nombre="Gestión de Base de Datos" horas="192">
                <Profesor>Montaña Morales</Profesor>
            </Modulo>
            <Modulo abbr="FOL" nombre="Formación y Orientación Laboral" horas="96">
                <Profesor>Marta Pérez</Profesor>
            </Modulo>
            <Modulo abbr="FHW" nombre="Fundamentos Hardware" horas="96">
                <Profesor>Tomás Montero</Profesor>
            </Modulo>
        </Modulos>
        <Horario>
            <Dia nombre="Lunes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="ISO"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="FOL" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="GBD" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="PARE" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="PARE" tipo="módulo" />
            </Dia>
            <Dia nombre="Martes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="ISO"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="ISO" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="GBD" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="PARE" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="PARE" tipo="módulo" />
            </Dia>
            <Dia nombre="Miércoles">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="ISO"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="PARE" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="FOL" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="GBD" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="GBD" tipo="módulo" />
            </Dia>
            <Dia nombre="Jueves">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="ISO" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="ISO"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="PARE" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="FOL" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="FHW" tipo="módulo" />
            </Dia>
            <Dia nombre="Viernes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="GBD" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="GBD"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="PARE" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="ISO" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="FHW" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="FHW" tipo="módulo" />
            </Dia>
        </Horario>
    </Grupo>
    <Grupo nombre="1º DAM">
        <Tutoria>
            <Dia nombre="Martes">
                <Periodo desde="15:20:00" hasta="16:15:00" />
            </Dia>
            <Profesor>Puerto Cruz</Profesor>
            <Observaciones><![CDATA[Concertar <em>cita previa</em> para evitar esperas.]]> </Observaciones>
        </Tutoria> 
        <Modulos>
            <Modulo abbr="LMSGI" nombre="Lenguaje de Marcas y Sistemas de Gestión de la Información"  horas="128">
                <Profesor>Antonio Berrocal Piris</Profesor>
            </Modulo>
            <Modulo abbr="SSII" nombre="Sistemas Informáticos" horas="192">
                <Profesor>Julio Barbero</Profesor>
            </Modulo>
            <Modulo abbr="BD" nombre="Base de Datos" horas="192">
                <Profesor>Puerto Cruz</Profesor>
            </Modulo>
            <Modulo abbr="PGRMC" nombre="Programación" horas="224">
                <Profesor>Enrique Pineda</Profesor>
            </Modulo>
            <Modulo abbr="FOL" nombre="Formación y Orientación Laboral" horas="96">
                <Profesor>Marta Pérez</Profesor>
            </Modulo>
            <Modulo abbr="ED" nombre="Entornos de Desarrollo" horas="128">
                <Profesor>M. Cristina Iglesias</Profesor>
            </Modulo>
        </Modulos>
        <Horario>
            <Dia nombre="Lunes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="BD" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="FOL"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="PGRMC" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="PGRMC" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="SI" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="SI" tipo="módulo" />
            </Dia>
            <Dia nombre="Martes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="PGRMC" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="PGRMC"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="ED" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="LMSGI" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="BD" tipo="módulo" />
            </Dia>
            <Dia nombre="Miércoles">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="FOL" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="PGRMC"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="ED" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="SI" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="SI" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="BD" tipo="módulo" />
            </Dia>
            <Dia nombre="Jueves">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="FOL" tipo="módulo" />
                <Periodo desde="16:15:00" hasta="17:10:00" abbr="BD"  tipo="módulo"/>
                <Periodo desde="17:10:00" hasta="18:05:00" abbr="BD" tipo="módulo" />
                <Periodo desde="18:05:00" hasta="18:25:00" abbr="Recreo" descripcion="Periodo de descanso" />
                <Periodo desde="18:25:00" hasta="19:20:00" abbr="BD" tipo="módulo" />
                <Periodo desde="19:20:00" hasta="20:15:00" abbr="ED" tipo="módulo" />
                <Periodo desde="20:15:00" hasta="21:10:00" abbr="ED" tipo="módulo" />
            </Dia>
            <Dia nombre="Viernes">
                <Periodo desde="15:20:00" hasta="16:15:00" abbr="PGRMC" tipo="módulo" />
