=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b5p1-vjp-walterML-master/ofertasempleo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Antonio Sanchez (CIEMAT) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Denominacion" type="xs:string">
		<xs:annotation>
			<xs:documentation>Denominación de la oferta de empleo</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Descripcion" type="xs:string">
		<xs:annotation>
			<xs:documentation>Descripción de la oferta de empleo</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Convocatoria" type="xs:string">
		<xs:annotation>
			<xs:documentation>Código de la convocatoria</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Situacion" type="xs:string">
		<xs:annotation>
			<xs:documentation>Situación en la que está la convocatoria</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Estado" type="xs:string">
		<xs:annotation>
			<xs:documentation>Estado de la convocatoria (Nueva, En proceso, Resuelta, etc.)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="TipoPlaza" type="xs:string">
		<xs:annotation>
			<xs:documentation>Tipo de convocatoria (Funcionario, Laboral, etc.)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="SistemaAdjudicacion" type="xs:string">
		<xs:annotation>
			<xs:documentation>Sistema de adjudicación de la convocatoria (Promoción interna, Acceso libre, etc.)</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Titulacion" type="xs:string">
		<xs:annotation>
			<xs:documentation>Titulación mí­nima requerida en la convocatoria</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="FechaPublicacion" type="xs:date">
		<xs:annotation>
			<xs:documentation>Fecha de publicación de la convocatoria</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="FechaModificacion" type="xs:date">
		<xs:annotation>
			<xs:documentation>Fecha de última modificación del estado de la convocatoria</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="URL" type="xs:string"/>
	<xs:element name="OfertaEmpleo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Denominacion"/>
				<xs:element ref="Descripcion" minOccurs="0"/>
				<xs:element ref="Convocatoria" minOccurs="0"/>
				<xs:element ref="Situacion" minOccurs="0"/>
				<xs:element ref="Estado" minOccurs="0"/>
				<xs:element ref="TipoPlaza" minOccurs="0"/>
				<xs:element ref="SistemaAdjudicacion" minOccurs="0"/>
				<xs:element ref="Titulacion" minOccurs="0"/>
				<xs:element ref="FechaPublicacion" minOccurs="0"/>
				<xs:element ref="FechaModificacion" minOccurs="0"/>
				<xs:element ref="URL" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OfertasEmpleo">
		<xs:annotation>
			<xs:documentation>Ofertas de empleo del Ciemat</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="OfertaEmpleo" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="FechaCreacion" type="xs:date"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b5p1-vjp-walterML-master/ofertasempleo.xml
<?xml version="1.0" encoding="UTF-8"?>
<OfertasEmpleo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" FechaCreacion="2022-02-02" xsi:noNamespaceSchemaLocation="ofertasempleo.xsd">
  <OfertaEmpleo id="id_1531">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación (Postdoctoral)</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior de Investigación (Postdoctoral)  Nivel D, fuera de convenio,  en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas de Madrid</Descripcion>
    <Convocatoria>17-CIEMAT-20</Convocatoria>
    <Situacion>Adjudicación</Situacion>
    <Estado>Resuelta</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Doctorado</Titulacion>
    <FechaPublicacion>2020-07-07</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1531</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1588">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación.</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior de Investigación , Nivel D, fuera de convenio,  en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas de Madrid</Descripcion>
    <Convocatoria>32-CIEMAT-20</Convocatoria>
    <Situacion>Lista provisional de aspirantes admitidos y excluidos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Titulado Superior o Grado</Titulacion>
    <FechaPublicacion>2020-09-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1588</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1559">
    <Denominacion>Una plaza de personal laboral temporal de la categoría de Titulado Superior</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior FC1, fuera de convenio, en Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas (CIEMAT) en Madrid</Descripcion>
    <Convocatoria>20-CIEMAT-20</Convocatoria>
    <Situacion>Adjudicación</Situacion>
    <Estado>Resuelta</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Titulado Superior o Grado</Titulacion>
    <FechaPublicacion>2020-07-10</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1559</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1515">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación (Postdoctoral)</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior de Investigación (Postdoctoral)  Nivel C, fuera de convenio,  en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas de Madrid</Descripcion>
    <Convocatoria>25-EUROFUSION-20</Convocatoria>
    <Situacion>Adjudicación</Situacion>
    <Estado>Resuelta</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Doctorado</Titulacion>
    <FechaPublicacion>2020-06-29</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1515</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1481">
    <Denominacion>ESCALA CIENTÍFICOS TITULARES DE LOS OPIS, ACCESO LIBRE, OEP 2018-2019</Denominacion>
    <Descripcion>Escala de Científicos Titulares de los OPIS, acceso libre, OEP 2018-2019</Descripcion>
    <Convocatoria>RESOLUCIÓN 25-11-2019 CT-TL (OEP 2018-2019)</Convocatoria>
    <Situacion>Puntuación segunda fase del Concurso</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Funcionario</TipoPlaza>
    <SistemaAdjudicacion>Acceso libre</SistemaAdjudicacion>
    <Titulacion>Doctorado</Titulacion>
    <FechaPublicacion>2019-12-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1481</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1587">
    <Denominacion>Una plaza de personal laboral temporal. Categoría Técnico Superior de Activ Técnicas y Profesionales</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Técnico Superior de Actividades Técnicas y Profesionales (Grupo 3), en la modalidad de obra o servicio, con cargo a proyecto de investigación, en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas en Madrid</Descripcion>
    <Convocatoria>35-CIEMAT-20</Convocatoria>
    <Situacion>Lista provisional de aspirantes admitidos y excluidos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Bachiller Sup.,BUP,FP II o eq.</Titulacion>
    <FechaPublicacion>2020-09-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1587</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1560">
    <Denominacion>Una plaza de personal laboral temporal. Categoría Técnico Superior de Activ Técnicas y Profesionales</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Técnico Superior de Actividades Técnicas y Profesionales (Grupo 3), en la modalidad de obra o servicio, con cargo a proyecto de investigación, en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas en Madrid</Descripcion>
    <Convocatoria>22-CIEMAT-20</Convocatoria>
    <Situacion>Lista definitiva de aspirantes que superan la puntuación mínima de la fase de concurso de méritos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Bachiller Sup.,BUP,FP II o eq.</Titulacion>
    <FechaPublicacion>2020-07-10</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1560</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1586">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación (Postdoctoral)</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior de Investigación (Postdoctoral)  Nivel D, fuera de convenio,  en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas de Madrid</Descripcion>
    <Convocatoria>31-CIEMAT-20</Convocatoria>
    <Situacion>Lista provisional de aspirantes admitidos y excluidos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Doctorado</Titulacion>
    <FechaPublicacion>2020-09-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1586</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1585">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación.</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior Nivel D, fuera de convenio, en Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas (CIEMAT) en Madrid</Descripcion>
    <Convocatoria>33-CIEMAT-20</Convocatoria>
    <Situacion>Lista provisional de aspirantes admitidos y excluidos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Titulado Superior o Grado</Titulacion>
    <FechaPublicacion>2020-09-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1585</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1584">
    <Denominacion>Una plaza de personal laboral temporal de categoría de Titulado Sup de Investigación.</Denominacion>
    <Descripcion>Una plaza de personal laboral temporal de la categoría de Titulado Superior de Investigación, Nivel D, fuera de convenio,  en el Centro de Investigaciones Energéticas, Medioambientales y Tecnológicas de Madrid</Descripcion>
    <Convocatoria>29-CIEMAT-20</Convocatoria>
    <Situacion>Lista provisional de aspirantes admitidos y excluidos</Situacion>
    <Estado>En proceso</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Titulado Superior o Grado</Titulacion>
    <FechaPublicacion>2020-09-04</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
    <URL>http://www.ciemat.es/cargarAplicacionOfertaEmpleo.do?identificador=1584</URL>
  </OfertaEmpleo>
  <OfertaEmpleo id="id_1628">
    <Denominacion>Una plaza de investigador predoctoral en formación</Denominacion>
    <Descripcion>Se convoca proceso selectivo para la contratación de personal investigador predoctoral en formación,  mediante la modalidad de contrato predoctoral, para su incorporación al proyecto: "Procesos de retención / migración de radionucleidos en almacenamientos de residuos radiactivos"</Descripcion>
    <Convocatoria>37-PREMM-20</Convocatoria>
    <Situacion>Bases</Situacion>
    <Estado>Nueva</Estado>
    <TipoPlaza>Laboral</TipoPlaza>
    <SistemaAdjudicacion>Concurso</SistemaAdjudicacion>
    <Titulacion>Titulado Superior o Grado</Titulacion>
    <FechaPublicacion>2020-10-22</FechaPublicacion>
    <FechaModificacion>2020-10-22</FechaModificacion>
