=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/empleados.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (id,firstname,lastName,photo)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT photo (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/empleados.xml
<!DOCTYPE employees SYSTEM "empleados.dtd">
<employees>
    <employee>
        <id>1</id>
        <firstname>Tom</firstname>
        <lastName>Cruise</lastName>
        <photo>sdfasd.jpg</photo>
    </employee>
    <employee>
        <id>2</id>
        <firstname>Maria</firstname>
        <lastName>Sharapova</lastName>
        <photo>sdfasdsd.jpg</photo>
    </employee>
    <employee>
        <id>3</id>
        <firstname>James</firstname>
        <lastName>Bond</lastName>
        <photo>sdfassdfdsdsd.jpg</photo>
    </employee>
</employees>
