=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/existenciasV2.dtd
<!ELEMENT ListaDeProductos (Producto+)>
<!ATTLIST ListaDeProductos hora NMTOKEN #REQUIRED>
<!ATTLIST ListaDeProductos dia NMTOKEN #REQUIRED>
<!ATTLIST ListaDeProductos mes NMTOKEN #REQUIRED>
<!ATTLIST ListaDeProductos anno NMTOKEN #REQUIRED>
<!ELEMENT Producto (Nombre,Stock)>
<!ATTLIST Producto codigoId NMTOKEN #REQUIRED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Stock (Minimo,Maximo)>
<!ATTLIST Stock actual NMTOKEN #REQUIRED>
<!ELEMENT Minimo (#PCDATA)>
<!ELEMENT Maximo (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/existenciasV2.xml
<!DOCTYPE ListaDeProductos SYSTEM "existenciasV2.dtd">
<ListaDeProductos hora="17:01" dia="14" mes="10" anno="2022">
    <Producto codigoId="1">
        <Nombre>Producto1</Nombre>
        <Stock actual="3">
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
    <Producto codigoId="2">
        <Nombre>Producto2</Nombre>
        <Stock actual="5">
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
    <Producto codigoId="3">
        <Nombre>Producto3</Nombre>
        <Stock actual="3">
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
</ListaDeProductos>
