=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/existenciasV1.dtd
<!ELEMENT ListaDeProductos (Producto+,UltimaActualizacion)>
<!ELEMENT Producto (CodigoId,Nombre,Stock)>
<!ELEMENT CodigoId (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Stock (Actual,Minimo,Maximo)>
<!ELEMENT Actual (#PCDATA)>
<!ELEMENT Minimo (#PCDATA)>
<!ELEMENT Maximo (#PCDATA)>
<!ELEMENT UltimaActualizacion (Dia,Mes,Anno,Hora)>
<!ELEMENT Dia (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>
<!ELEMENT Anno (#PCDATA)>
<!ELEMENT Hora (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/existenciasV1.xml
<!DOCTYPE ListaDeProductos SYSTEM "existenciasV1.dtd">
<ListaDeProductos>
    <Producto>
        <CodigoId>1</CodigoId>
        <Nombre>Producto1</Nombre>
        <Stock>
            <Actual>3</Actual>
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
    <Producto>
        <CodigoId>2</CodigoId>
        <Nombre>Producto2</Nombre>
        <Stock>
            <Actual>5</Actual>
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
    <Producto>
        <CodigoId>3</CodigoId>
        <Nombre>Producto3</Nombre>
        <Stock>
            <Actual>3</Actual>
            <Minimo>1</Minimo>
            <Maximo>10</Maximo>
        </Stock>
    </Producto>
    <UltimaActualizacion>
        <Dia>14</Dia>
        <Mes>10</Mes>
        <Anno>2022</Anno>
        <Hora>17:01</Hora>
    </UltimaActualizacion>
</ListaDeProductos>
