=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/horarios.dtd
<!ELEMENT Grupos (Centro,Url,Curso,Grupo+)>
<!ELEMENT Centro (#PCDATA)>
<!ELEMENT Url (#PCDATA)>
<!ELEMENT Curso (#PCDATA)>
<!ELEMENT Grupo (Nombre,Tutoria,Asignaturas,Horario)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Tutoria (Profesor,Tramo)>
<!ELEMENT Profesor (#PCDATA)>
<!ELEMENT Tramo (Id,HoraInicio,HoraFin,Dias)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT HoraInicio (#PCDATA)>
<!ELEMENT HoraFin (#PCDATA)>
<!ELEMENT Dias (Dia+)>
<!ELEMENT Dia (Nombre,Abreviatura)>
<!ELEMENT Abreviatura (#PCDATA)>
<!ELEMENT Asignaturas (Asignatura+)>
<!ELEMENT Asignatura (Abreviatura,Nombre,Horas,Profesor)>
<!ELEMENT Horas (#PCDATA)>
<!ELEMENT Horario (Tramos)>
<!ELEMENT Tramos (Tramo+)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/horarios.xml
<!DOCTYPE Grupos SYSTEM "horarios.dtd">
<Grupos>
    <Centro>IES Valle del Jerte</Centro>
    <Url>https://iesvallejertepla.educarex.es/</Url>
    <Curso>2022-2023</Curso>
    <!-- ASIR -->
    <Grupo>
        <Nombre>1ºGS-Administración de Sistemas Informáticos en Red</Nombre>
        <Tutoria>
            <Profesor>Fátima Hontiveros Almaraz</Profesor>
            <Tramo>
                <Id>4</Id>
                <HoraInicio>18:25</HoraInicio>
                <HoraFin>19:20</HoraFin>
                <Dias>
                    <Dia>
                        <Nombre>Martes</Nombre>
                        <Abreviatura>LMSGI</Abreviatura>
                    </Dia>
                </Dias>
            </Tramo>
        </Tutoria>
        

        <!-- ASIGNATURAS -->

        <Asignaturas>
            <Asignatura>
                <Abreviatura>ISO</Abreviatura>
                <Nombre>Implantación de Sistemas Operativos</Nombre>
                <Horas>224</Horas>
                <Profesor>Antonio Berrocal</Profesor>
            </Asignatura>
            <Asignatura>
                <Abreviatura>PARE</Abreviatura>
                <Nombre>Planificación y Administración de Redes</Nombre>
                <Horas>224</Horas>
                <Profesor>Marian Valdera</Profesor>
            </Asignatura>
            <Asignatura>
                <Abreviatura>FHW</Abreviatura>
                <Nombre>Fundamentos de Hardware</Nombre>
                <Horas>96</Horas>
                <Profesor>Fernando Torrecilla</Profesor>
            </Asignatura>
            <Asignatura>
                <Abreviatura>GBD</Abreviatura>
                <Nombre>Gestión de Bases de Datos</Nombre>
                <Horas>192</Horas>
                <Profesor>Marcos Fernández</Profesor>
            </Asignatura>
            <Asignatura>
                <Abreviatura>LMSGI</Abreviatura>
                <Nombre>Lenguajes de Marca y Sistemas de Gestión de Inf.</Nombre>
                <Horas>128</Horas>
                <Profesor>Antonio Berrocal</Profesor>
            </Asignatura>
            <Asignatura>
                <Abreviatura>FOL</Abreviatura>
                <Nombre>Formación y Orientación Laboral</Nombre>
                <Horas>96</Horas>
                <Profesor>Fátima Hontiveros</Profesor>
            </Asignatura>
        </Asignaturas>

        <!-- HORARIO -->

        <Horario>
            <Tramos>
                <Tramo>
                    <Id>1</Id>
                    <HoraInicio>15:20</HoraInicio>
                    <HoraFin>16:15</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>FHW</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
                <Tramo>
                    <Id>2</Id>
                    <HoraInicio>16:15</HoraInicio>
                    <HoraFin>17:10</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>LMSGI</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>FHW</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>FHW</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
                <Tramo>
                    <Id>3</Id>
                    <HoraInicio>17:10</HoraInicio>
                    <HoraFin>18:05</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>FOL</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>LMSGI</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
                <Tramo>
                    <Id>4</Id>
                    <HoraInicio>18:25</HoraInicio>
                    <HoraFin>19:20</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>LMSGI</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>LMSGI</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
                <Tramo>
                    <Id>5</Id>
                    <HoraInicio>19:20</HoraInicio>
                    <HoraFin>20:15</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>FOL</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
                <Tramo>
                    <Id>6</Id>
                    <HoraInicio>20:15</HoraInicio>
                    <HoraFin>21:10</HoraFin>
                    <Dias>
                        <Dia>
                            <Nombre>Lunes</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Martes</Nombre>
                            <Abreviatura>ISO</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Miércoles</Nombre>
                            <Abreviatura>FOL</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Jueves</Nombre>
                            <Abreviatura>PARE</Abreviatura>
                        </Dia>
                        <Dia>
                            <Nombre>Viernes</Nombre>
                            <Abreviatura>GBD</Abreviatura>
                        </Dia>
                    </Dias>
                </Tramo>
            </Tramos>
        </Horario>
    </Grupo>
    <!-- DAM -->
    <Grupo>
        <Nombre>1ºGS-Desarrollo de Aplicaciones Multiplataforma</Nombre>
        <Tutoria>
            <Profesor>Puerto Cruz Mateos</Profesor>
            <Tramo>
                <Id>2</Id>
                <HoraInicio>16:15</HoraInicio>
                <HoraFin>17:10</HoraFin>
                <Dias>
                    <Dia>
                        <Nombre>Martes</Nombre>
                        <Abreviatura>BBDD</Abreviatura>
                    </Dia>
                    <Dia>
                        <Nombre>Jueves</Nombre>
                        <Abreviatura>BBDD</Abreviatura>
                    </Dia>
                </Dias>
            </Tramo>
        </Tutoria>

        <!-- ASIGNATURAS -->

        <Asignaturas>
            <Asignatura>
                <Abreviatura>SSINF</Abreviatura>
                <Nombre>Sistemas Informáticos</Nombre>
                <Horas>192</Horas>
