=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/menu.dtd
<!ELEMENT menu_almuerzo (comida+)>
<!ELEMENT comida (nombre,precio,descripcion)>
<!ATTLIST comida calorias NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/menu.xml
<!DOCTYPE menu_almuerzo SYSTEM "menu.dtd">
<menu_almuerzo>
    <comida calorias="650">
		<nombre>Waffles</nombre>
		<precio>2.00</precio>
		<descripcion>Waffles baratos de McDonalds</descripcion>
    </comida>
    <comida calorias="1500">
		<nombre>Hamburguesa</nombre>
		<precio>5.00</precio>
		<descripcion>La hamburguesa mas com√∫n de McDonalds</descripcion>
    </comida>    
</menu_almuerzo>
