=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/plantas.dtd
<!ELEMENT CATALOGO (PLANTA+)>
<!ELEMENT PLANTA (NOMBRE_COMUN,NOMBRE_CIENTIFICO,ZONA,LIGHT,PRECIO,DISPONIBILIDAD)>
<!ELEMENT NOMBRE_COMUN (#PCDATA)>
<!ELEMENT NOMBRE_CIENTIFICO (#PCDATA)>
<!ELEMENT ZONA (#PCDATA)>
<!ELEMENT LIGHT (#PCDATA)>
<!ELEMENT PRECIO (#PCDATA)>
<!ELEMENT DISPONIBILIDAD (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/plantas.xml
<!DOCTYPE CATALOGO SYSTEM "plantas.dtd">
<CATALOGO>
    <PLANTA>
        <NOMBRE_COMUN>1</NOMBRE_COMUN>
        <NOMBRE_CIENTIFICO>ASDF</NOMBRE_CIENTIFICO>
        <ZONA>ZONA 1</ZONA>
        <LIGHT>L1</LIGHT>
        <PRECIO>99</PRECIO>
        <DISPONIBILIDAD>D1</DISPONIBILIDAD>
    </PLANTA>
    <PLANTA>
        <NOMBRE_COMUN>2</NOMBRE_COMUN>
        <NOMBRE_CIENTIFICO>ASDFASD</NOMBRE_CIENTIFICO>
        <ZONA>ZONA 2</ZONA>
        <LIGHT>L2</LIGHT>
        <PRECIO>100</PRECIO>
        <DISPONIBILIDAD>D2</DISPONIBILIDAD>
    </PLANTA>
    <PLANTA>
        <NOMBRE_COMUN>3</NOMBRE_COMUN>
        <NOMBRE_CIENTIFICO>ASDdfsFASD</NOMBRE_CIENTIFICO>
        <ZONA>ZONA 3</ZONA>
        <LIGHT>L3</LIGHT>
        <PRECIO>130</PRECIO>
        <DISPONIBILIDAD>D3</DISPONIBILIDAD>
    </PLANTA>
    <PLANTA>
        <NOMBRE_COMUN>4</NOMBRE_COMUN>
        <NOMBRE_CIENTIFICO>ASdfgasdfDFASD</NOMBRE_CIENTIFICO>
        <ZONA>ZONA 4</ZONA>
        <LIGHT>L4</LIGHT>
        <PRECIO>140</PRECIO>
        <DISPONIBILIDAD>D4</DISPONIBILIDAD>
    </PLANTA>
    
</CATALOGO>
