=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/Examenes/ex1_dic22-vjp-walterML-master/dgt/dgt.dtd
<!ELEMENT Incidencias (Incidencia+)>
<!ELEMENT Incidencia (Id,Tipo,Causa,Nivel,Sentido,Localizacion,Fecha,Pk)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Tipo (#PCDATA)>
<!ELEMENT Causa (#PCDATA)>
<!ELEMENT Nivel (#PCDATA)>
<!ELEMENT Sentido (#PCDATA)>
<!ELEMENT Localizacion (Autonomia,Provincia,Poblacion,Coordenadas)>
<!ELEMENT Autonomia (#PCDATA)>
<!ELEMENT Provincia (#PCDATA)>
<!ELEMENT Poblacion (#PCDATA)>
<!ELEMENT Coordenadas (CoordenadaX,CoordenadaY)>
<!ELEMENT CoordenadaX (#PCDATA)>
<!ELEMENT CoordenadaY (#PCDATA)>
<!ELEMENT Fecha (Ano,Mes,Dia,Hora)>
<!ELEMENT Ano (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>
<!ELEMENT Dia (#PCDATA)>
<!ELEMENT Hora (#PCDATA)>
<!ELEMENT Pk (Inicial,Final)>
<!ELEMENT Inicial (#PCDATA)>
<!ELEMENT Final (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/Examenes/ex1_dic22-vjp-walterML-master/dgt/dgt.xml
<!DOCTYPE Incidencias SYSTEM "dgt.dtd">
<Incidencias>
    <Incidencia>
        <Id>1</Id>
        <Tipo>Metorológica</Tipo>
        <Causa>Niebla</Causa>
        <Nivel>Verde</Nivel>
        <Sentido>Ambos sentidos</Sentido>
        <Localizacion>
            <Autonomia>Castilla y León</Autonomia>
            <Provincia>Zamora</Provincia>
            <Poblacion>Zamora</Poblacion>
            <Coordenadas>
                <CoordenadaX>41.51757</CoordenadaX>
                <CoordenadaY>-5.23385</CoordenadaY>
            </Coordenadas>
        </Localizacion>
        <Fecha>
            <Ano>2017</Ano>
            <Mes>11</Mes>
            <Dia>27</Dia>
            <Hora>11:07</Hora>
        </Fecha>
        <Pk>
            <Inicial>412.0</Inicial>
            <Final>455.0</Final>
        </Pk>
    </Incidencia>
    <Incidencia>
        <Id>2</Id>
        <Tipo>Obras</Tipo>
        <Causa>Obras en General</Causa>
        <Nivel>Negro</Nivel>
        <Sentido>Ambos sentidos</Sentido>
        <Localizacion>
            <Autonomia>Extremadura</Autonomia>
            <Provincia>Badajoz</Provincia>
            <Poblacion>Valdivia</Poblacion>
            <Coordenadas>
                <CoordenadaX>39.0338029</CoordenadaX>
                <CoordenadaY>-5.7104669</CoordenadaY>
            </Coordenadas>
        </Localizacion>
        <Fecha>
            <Ano>2017</Ano>
            <Mes>11</Mes>
            <Dia>17</Dia>
            <Hora>11:00</Hora>
        </Fecha>
        <Pk>
            <Inicial>0.0</Inicial>
            <Final>5.0</Final>
        </Pk>
    </Incidencia>
    <Incidencia>
        <Id>3</Id>
        <Tipo>Obras</Tipo>
        <Causa>Trabajos de mantenimiento</Causa>
        <Nivel>Amarillo</Nivel>
        <Sentido>Ambos sentidos</Sentido>
        <Localizacion>
            <Autonomia>Extremadura</Autonomia>
            <Provincia>Badajoz</Provincia>
            <Poblacion>Valverde de Leganés</Poblacion>
            <Coordenadas>
                <CoordenadaX>38.51993</CoordenadaX>
                <CoordenadaY>-6.85655</CoordenadaY>
            </Coordenadas>
        </Localizacion>
        <Fecha>
            <Ano>2017</Ano>
            <Mes>11</Mes>
            <Dia>27</Dia>
            <Hora>08:00</Hora>
        </Fecha>
        <Pk>
            <Inicial>0.0</Inicial>
            <Final>21.0</Final>
        </Pk>
    </Incidencia>
</Incidencias>
