=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/ejemplos/ejemplo1.dtd
<!ELEMENT fichas (ficha+)>
<!ELEMENT ficha (nombre,apellido,direccion)>
<!ATTLIST ficha numero NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== wmlopes0/DAM/1Daw/LMSGI/Repositorios/b1p5-vjp-walterML-master/ejemplos/ejemplo1.xml
<!DOCTYPE fichas SYSTEM "ejemplo1.dtd">
<fichas>
    <ficha numero="1">
        <nombre> Walter </nombre>
        <apellido> Martín </apellido>
        <direccion> Calle Níscalo 9 </direccion>
    </ficha>
    <ficha numero="2">
        <nombre> Gabriel </nombre>
        <apellido> Molina </apellido>
        <direccion> Alfredo Vargas #36 </direccion>
    </ficha>
</fichas>
